# fly.toml app configuration file generated for anibalandrade on 2023-10-22T10:03:58-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "anibalandrade"
primary_region = "lax"

[build]

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
